# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/zybo_1B/zybo_1B.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B || ORIG_REF_NAME==zybo_1B} -quiet] -quiet

# IP: bd/zybo_1B/ip/zybo_1B_processing_system7_0_1/zybo_1B_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B_processing_system7_0_1 || ORIG_REF_NAME==zybo_1B_processing_system7_0_1} -quiet] -quiet

# IP: bd/zybo_1B/ip/zybo_1B_axi_gpio_0_1/zybo_1B_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B_axi_gpio_0_1 || ORIG_REF_NAME==zybo_1B_axi_gpio_0_1} -quiet] -quiet

# IP: bd/zybo_1B/ip/zybo_1B_ps7_0_axi_periph_2/zybo_1B_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B_ps7_0_axi_periph_2 || ORIG_REF_NAME==zybo_1B_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/zybo_1B/ip/zybo_1B_rst_ps7_0_50M_2/zybo_1B_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B_rst_ps7_0_50M_2 || ORIG_REF_NAME==zybo_1B_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/zybo_1B/ip/zybo_1B_auto_pc_2/zybo_1B_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_1B_auto_pc_2 || ORIG_REF_NAME==zybo_1B_auto_pc_2} -quiet] -quiet

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_1B/zybo_1B.gen/sources_1/bd/zybo_1B/zybo_1B_ooc.xdc
