# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.srcs/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0.xci
# IP: The module: 'interput_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.gen/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interput_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.gen/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interput_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.srcs/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0.xci
# IP: The module: 'interput_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.gen/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interput_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.gen/sources_1/bd/interput/ip/interput_axi_timer_0_0/interput_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interput_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
