# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/interput/interput.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput || ORIG_REF_NAME==interput} -quiet] -quiet

# IP: bd/interput/ip/interput_processing_system7_0_0/interput_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_processing_system7_0_0 || ORIG_REF_NAME==interput_processing_system7_0_0} -quiet] -quiet

# IP: bd/interput/ip/interput_axi_gpio_0_0/interput_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_axi_gpio_0_0 || ORIG_REF_NAME==interput_axi_gpio_0_0} -quiet] -quiet

# IP: bd/interput/ip/interput_axi_gpio_0_1/interput_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_axi_gpio_0_1 || ORIG_REF_NAME==interput_axi_gpio_0_1} -quiet] -quiet

# IP: bd/interput/ip/interput_xbar_0/interput_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_xbar_0 || ORIG_REF_NAME==interput_xbar_0} -quiet] -quiet

# IP: bd/interput/ip/interput_ps7_0_axi_periph_0/interput_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_ps7_0_axi_periph_0 || ORIG_REF_NAME==interput_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/interput/ip/interput_rst_ps7_0_50M_0/interput_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_rst_ps7_0_50M_0 || ORIG_REF_NAME==interput_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/interput/ip/interput_auto_pc_0/interput_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interput_auto_pc_0 || ORIG_REF_NAME==interput_auto_pc_0} -quiet] -quiet

# XDC: /home/trevin/Documents/Soc_Projects/zybo_excrises/zybo_exercise_2/zybo_exercise_2.gen/sources_1/bd/interput/interput_ooc.xdc
